# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: '2.1'
executors:
  docker-executor:
    docker:
      - image: circleci/node:14.18.1
jobs:
  pre_build:
    working_directory: ~/graphAPI
    description: Prebuild steps to follow before docker
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - ${CIRCLE_PROJECT_REPONAME}-{{checksum "package-lock.json"}}
      - save_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{checksum "package-lock.json"}}
          paths:
              - ~/graphAPI/.cache
      - run:
          name: "GraphAPI run"
          command: |
            node --version
            npm --version
            npm install
            mkdir -p workspace/build-target/
            npm run build:graphql:dev:circleci

            cp -r ./apps ./workspace/build-target/
            cp -r ./libs ./workspace/build-target/
            cp -r *.json ./workspace/build-target/
            cp -r ./target ./workspace/build-target/
            cp -r ./node_modules ./workspace/build-target/

      - persist_to_workspace:
          paths:
            - build-target
          root: workspace

  docker_build:
    working_directory: ~/graphAPI
    description: Docker build
    docker:
      - image: alpine:3.12.0
    steps:

      - setup_remote_docker
      - run:
          name: INstall docker client
          command: |
            apk add --no-cache ca-certificates
            mkdir /usr/share/ca-certificates/extra
            update-ca-certificates
            set -x
            apk add --no-cache docker-cli python3 py3-pip
            apk add --no-cache --virtual .docker-compose-deps python3-dev libffi-dev openssl-dev gcc libc-dev make
            docker version
            docker ps
            pip3 install docker-compose
            apk del .docker-compose-deps
            docker-compose version
      - attach_workspace:
          at: ~/graphAPI/workspace/
      - run:
          name: "Docker build"
          command: |
            ls -lta && pwd
            cd ~/graphAPI/workspace/build-target
            ls -lta && pwd
            export TAG=0.1.$CIRCLE_BUILD_NUM
            export LOCAL_APP_NAME=$APP_NAME
            echo $LOCAL_APP_NAME
            docker build -f apps/graphql/src/deployment/docker-manifest/Dockerfile -t ci-graphapi:${TAG} .
workflows:
  app_docker_ci:
    jobs:
      - pre_build
      - docker_build:
          requires:
            - pre_build