# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: '2.1'
jobs:
  pre_build:
    description: Prebuild steps to follow before docker
    working_directory: ~/.app
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - ${CIRCLE_PROJECT_REPONAME}-{{checksum "package-lock.json"}}
      - save_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{checksum "package-lock.json"}}
          paths:
              - /app/.cache
      - run:
          name: "GraphAPI run"
          command: |
            node --version
            npm --version
            ls -lta && pwd
            npm install
            npm run build:graphql:dev:circleci
            bash apt install rsync
            cp -r . .

      - persist_to_workspace:
          paths:
            - ./
          root: ~/.app

  docker_build:
    working_directory: ~/.app
    description: Docker build
    docker:
      - image: circleci/node:14.18.1
    steps:
      - restore_cache:
          keys:
            - ${CIRCLE_PROJECT_REPONAME}-{{checksum "package-lock.json"}}
      - save_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{checksum "package-lock.json"}}
          paths:
            - /app/.cache
      - attach_workspace:
          at: ~/.app
      - checkout
      - run:
          name: "Docker build"
          command: |
            export TAG=0.1.$CIRCLE_BUILD_NUM
            export LOCAL_APP_NAME=$APP_NAME
            echo $LOCAL_APP_NAME
            docker build -f apps/graphql/src/deployment/docker-manifest/Dockerfile -t ci-graphapi:${TAG} .
workflows:
  app_docker_ci:
    jobs:
      - pre_build
      - docker_build:
          requires:
            - pre_build