# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: '2.1'

jobs:
  pre_build:
    description: Prebuild steps to follow before docker
    working_directory: ~/.app
    docker:
      - image: node:14-alpine3.13
    steps:
      - checkout
      - run:
          name: "GraphAPI run"
          command: |
            node --version
            npm --version
            export TAG=0.1.$CIRCLE_BUILD_NUM
            echo $TAG
            npm install
            ls -lta
            cd $CIRCLE_PROJECT_REPONAME
            npm run build:graphql:dev
  docker_build:
    working_directory: ~/.app
    description: Docker build
    docker:
      - image: node:14-alpine3.13
    steps:
      - run:
          name: "Docker build"
          command: |
            docker build -f apps/graphql/src/deployment/docker-manifest/Dockerfile -t ci-graphAPI:${TAG} .
            echo ${PROJECT_ID}
workflows:
  app_docker_ci:
    jobs:
      - pre_build
      - docker_build:
          requires:
            - pre_build