# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: '2.1'
jobs:
  pre_build:
    description: Prebuild steps to follow before docker
    working_directory: ~/.app
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - run:
          name: "GraphAPI run"
          command: |
            node --version
            npm --version
            export TAG=0.1.$CIRCLE_BUILD_NUM
            echo $TAG
            npm install
            rm -rf target
            rm -rf dist
            cd apps/graphql/src/build
            chmod +x apps/graphql/src/build/
            bash ./build.sh
  docker_build:
    working_directory: ~/.app
    description: Docker build
    docker:
      - image: circleci/node:14.18.1
    steps:
      - run:
          name: "Docker build"
          command: |
            docker build -f apps/graphql/src/deployment/docker-manifest/Dockerfile -t ci-graphAPI:${TAG} .
            echo ${PROJECT_ID}
workflows:
  app_docker_ci:
    jobs:
      - pre_build
      - docker_build:
          requires:
            - pre_build