# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: '2.1'
jobs:
  pre_build:
    description: Prebuild steps to follow before docker
    working_directory: ~/.app
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - run:
          name: "GraphAPI run"
          command: |
            node --version
            npm --version
            npm install
            mkdir -p /app/$APP_NAME/build-target
            npm run build:graphql:dev:circleci > build-target/

      - store_artifacts:
          path: /app/$APP_NAME/build-target/
          destination: target

  docker_build:
    working_directory: ~/.app
    description: Docker build
    docker:
      - image: circleci/node:14.18.1
    steps:
      - checkout
      - run:
          name: "Docker build"
          command: |
            export TAG=0.1.$CIRCLE_BUILD_NUM
            export LOCAL_APP_NAME=$APP_NAME
            echo $LOCAL_APP_NAME
            docker build -f apps/graphql/src/deployment/docker-manifest/Dockerfile -t ci-graphapi:${TAG} .
workflows:
  app_docker_ci:
    jobs:
      - pre_build
      - docker_build:
          requires:
            - pre_build