export const APP_CONST = {
	MANDATORY_HEADERS_NAME_LIST: ['CI-LOG-TRACKING-ID', 'CI-USER-TYPE', 'CI-CONSUMER-APP-PROCESS', 'CI-PRINCIPAL-ROLE'],
	HEADERS: {
		CI_LOG_TRACKING_ID: 'CI-LOG-TRACKING-ID',
		CI_USER_ID: 'CI-USER-ID',
		CI_USER_TYPE: 'CI-USER-TYPE',
		CI_PRINCIPAL_ROLE: 'CI-PRINCIPAL-ROLE',
		CI_CONSUMER_APP_PROCESS: 'CI-CONSUMER-APP-PROCESS',
	},
	CHAR: {
		COMMA: ',',
		SLASH: '/',
		COLON: ':',
		SEMI_COLON: ';',
		HYPHEN: '-',
		AT: '@',
		UNDERSCORE: '_',
		QUESTION: '?',
		DOT: '.',
	},
	COMMON: {
		REDACT: ['headers["Content-type"]', 'req["headers"]["Authorization"]'],
		APP_NAME: 'fastify-graphql',
		DEFAULT_APP_PORT: 3002,
		DEFAULT_APP_HOST: '0.0.0.0',
		APP_CONTEXT: '/graph-api',
		DEFAULT_DATE_TIME_FORMAT: 'yyyy-MM-dd HH:mm:ss.SSSS',
	},
	CORS: {
		HEADERS: ['Access-Control-Allow-Origin', 'Access-Control-Allow-Methods', 'Access-Control-Allow-Headers', 'Access-Control-Max-Age', 'Access-Control-Allow-Credentials'],
		WHITELIST: ['127.0.0.0', '127.0.0.0:3002', 'localhost:3002', '0.0.0.0:3002', '*'],
		ALLOW_HEADERS: ['Content-type', 'Authorization', 'Origin', 'X-Forwaded-for', 'Referrer', 'Origin'],
		ALLOW_METHODS: ['GET', 'POST', 'OPTIONS', 'PUT', 'DELETE'],
		ALLOW_CRED: true,
	},
	HEALTH_CHECK: {
		URL: 'https://jsonplaceholder.typicode.com/posts/1',
		METHOD: 'GET',
		PROXY: 'http://http.proxy.fmr.com:8000',
	},
	MIMETYPE: {
		APPLICATION_JSON: 'application/json',
		MULTIPART_FORM_DATA: 'multipart/form-data',
	},
	REGEX: {
		MULTIPART_CONTENT_TYPE: /^(multipart)[\/\\\-\w]*$/,
		FILE_NAME: /^[\w]{2,}(.(csv|xls|xlsx|env|mp4))$/,
		NUMBER: /^[\d]$/,
	},
};
